# Lecture Linear Equations

In [29]:
import numpy as np

epss = np.finfo(np.float32).eps
print("Machine epeilon for single precision : ",epss)
epsd = np.finfo(np.float64).eps
print("Machine epeilon for double precision : ",epsd)


Machine epeilon for single precision :  1.1920929e-07
Machine epeilon for double precision :  2.220446049250313e-16


In [35]:

realmaxd = np.finfo(np.float64).max
print("Max real number for double precision : ",realmaxd)


Max real number for double precision :  1.7976931348623157e+308


In [34]:
realmind = np.finfo(np.float64).min
print("Min real number for double precision : ",realmind)


Min real number for double precision :  -1.7976931348623157e+308


In [40]:
realzero = np.finfo(np.float64).tiny
print("Machine zero for double precision    : ",realzero/2**53)

Machine zero for double precision    :  0.0


In [47]:
print(1+epsd/2-1)

0.0


In [56]:
A = np.array([[-3, 2, 3], [-3,2 ,1], [3, 0, 0]])
b = np.array([10, 8, -3])
x = np.linalg.solve(A,b)
print(x)

[-1.  2.  1.]


In [62]:
n = 1000
A = np.random.rand(n,n)
b = np.random.rand(n)
x = np.linalg.solve(A,b)
#print(x)

In [55]:
x2 = np.linalg.inv(A) @ b
print('solution of Ax=b is\n')
print(x2)

[-1.  2.  1.]


In [64]:
N, M= 5,2
AA = np.random.rand(N,N)
bb = np.random.rand(N,1)
for i in range(N):
    for j in range(N):
        if abs(i-j)>1:
            AA[i,j]=0

            
x2=np.linalg.solve(AA,bb)
print('solution of Ax=b is\n')
print(x2)


 

solution of Ax=b is

[[ 1.88868544]
 [-2.15769452]
 [ 1.03355709]
 [ 1.48097895]
 [-1.01892402]]


In [65]:
import scipy as sci

AS = sci.sparse.csc_matrix(AA)
xs = sci.sparse.linalg.spsolve(AS,bb)
print('solution of sparse Ax=b is\n')
print(xs)

solution of sparse Ax=b is

[ 1.88868544 -2.15769452  1.03355709  1.48097895 -1.01892402]


In [66]:
# see Foundations of Applied Mathematics Volume 1 Mathematical Analysis Chapter 15
Ai =np.matrix([[2, 0, -1], [-1, 3, 2], [0, 1, 3]])
print(Ai)
bi = np.matrix([[3],[3], [-1]])


[[ 2  0 -1]
 [-1  3  2]
 [ 0  1  3]]


In [67]:
Q=np.matrix([[2, 0 , 0], [0, 3, 0],[0, 0, 3]])
print(Q)
Qi=np.matrix([[1/2, 0 , 0], [0, 1/3, 0],[0, 0, 1/3]])
print(Qi)


[[2 0 0]
 [0 3 0]
 [0 0 3]]
[[0.5        0.         0.        ]
 [0.         0.33333333 0.        ]
 [0.         0.         0.33333333]]


In [68]:
xi=np.random.rand(3,1)
for i in range(50):
#    xi = Qi @ ((Q-Ai) @ xi + bi)
    xi = xi + Qi @ (bi- Ai @ xi)
print('solution of Ax=b is\n')
print(xi)

solution of Ax=b is

[[ 1.]
 [ 2.]
 [-1.]]
